function love.load()
    Sprites = {}
    Sprites.logoPathLarge = love.graphics.newImage('sprites/logo512x.png')
    Sprites.chars = {}
    Sprites.chars.a = love.graphics.newImage('sprites/chars/a.png')
    Sprites.chars.b = love.graphics.newImage('sprites/chars/b.png')
    Sprites.chars.c = love.graphics.newImage('sprites/chars/c.png')
    Sprites.chars.d = love.graphics.newImage('sprites/chars/d.png')
    Sprites.chars.e = love.graphics.newImage('sprites/chars/e.png')
    Sprites.chars.f = love.graphics.newImage('sprites/chars/f.png')
    Sprites.chars.g = love.graphics.newImage('sprites/chars/g.png')
    Sprites.chars.h = love.graphics.newImage('sprites/chars/h.png')
    Sprites.chars.i = love.graphics.newImage('sprites/chars/i.png')
    Sprites.chars.j = love.graphics.newImage('sprites/chars/k.png')
    Sprites.chars.l = love.graphics.newImage('sprites/chars/l.png')
    Sprites.chars.m = love.graphics.newImage('sprites/chars/m.png')
    Sprites.chars.n = love.graphics.newImage('sprites/chars/n.png')
    Sprites.chars.o = love.graphics.newImage('sprites/chars/p.png')
    Sprites.chars.p = love.graphics.newImage('sprites/chars/p.png')
    Sprites.chars.q = love.graphics.newImage('sprites/chars/q.png')
    Sprites.chars.r = love.graphics.newImage('sprites/chars/r.png')
    Sprites.chars.s = love.graphics.newImage('sprites/chars/s.png')
    Sprites.chars.t = love.graphics.newImage('sprites/chars/t.png')
    Sprites.chars.u = love.graphics.newImage('sprites/chars/u.png')
    Sprites.chars.v = love.graphics.newImage('sprites/chars/v.png')
    Sprites.chars.w = love.graphics.newImage('sprites/chars/w.png')
    Sprites.chars.x = love.graphics.newImage('sprites/chars/x.png')
    Sprites.chars.y = love.graphics.newImage('sprites/chars/y.png')
    Sprites.chars.z = love.graphics.newImage('sprites/chars/z.png')
    --this is spaghetti
end
function love.draw()
    love.graphics.draw(Sprites.logoPathLarge, 0, 0)
end 